
development:
  dialect: postgres
  database: ENSETService
  user: postgres
  password: janah
  host: 0.0.0.0
  pool: 5

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:janah@0.0.0.0:5432/ENSETService?sslmode=disable"}}
