---
development:
  dialect: postgres
  database: ENSETService
  user: ensetse_user
  password: janah
  host: 127.0.0.1
  pool: 5

production:
  url: {{envOr "DATABASE_URL" "postgres://ensetse_user:janah@127.0.0.1:5432/ENSETService?sslmode=disable"}}
